Repository ms-club-sliit/msclub-backend, pull requests merged in 2021-12, with the labels that each got.

#79 Fixed the bugs in Webinar Service
  src/api/services/Webinar.service.ts
Labels: fix

#85 This closes #82 reviewing application email template created
  src/templates/Reviewing-Application-Email-Template.html
Labels: medium-priority, feature

#86 Feature/email template storage bucket
  .gitignore
  package-lock.json
  package.json
  src/api/controllers/Contact.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IConfig.ts
  src/config/.env.development
  src/config/.env.production
  src/config/firebase.config.ts
  src/config/index.ts
  src/config/service-account-file.json
  src/config/storage.config.ts
  src/templates/Email-Template.html
  src/util/email.handler.ts
  src/util/image.handler.ts
Labels: enhancement, high-priority, feature

#87 Created HTML email template for interview
  src/templates/Interview-Email-Template.html
Labels: feature

#89 Development into Main branch
  src/templates/Interview-Email-Template.html
Labels: medium-priority

#90 Remove customized email templates
  src/templates/Interview-Email-Template.html
  src/templates/Reviewing-Application-Email-Template.html
Labels: enhancement, medium-priority

#92 Application Form Controllers and Routes Created
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/index.ts
Labels: feature

#94 Development
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/index.ts
  src/util/email.handler.ts
Labels: bug, high-priority

#98 Change academic year type from number to string
  src/api/interfaces/IApplication.ts
  src/api/models/Application.model.ts
Labels: enhancement, high-priority

#99 Add Email Services into AddApplication Method
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IInterview.ts
  src/api/interfaces/index.ts
  src/api/models/Application.model.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/index.ts
  src/util/email.handler.ts
Labels: feature

#103 Implemented application status change to selected
  package-lock.json
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/index.ts
Labels: feature

#106 Application status into rejected feature added
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/index.ts
Labels: feature

#115 Implement add user and login user controllers
  src/api/controllers/User.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IUser.ts
  src/api/interfaces/index.ts
  src/api/models/User.model.ts
  src/api/routes/index.ts
  src/api/services/User.service.ts
  src/api/services/index.ts
Labels: enhancement, high-priority, fix

#114 Enhancement/change user model
  package-lock.json
  src/api/interfaces/IUser.ts
  src/api/services/User.service.ts
Labels: enhancement, high-priority, fix, feature

#123 Fix the Production Server fail Issue
  .gitignore
  package-lock.json
  package.json
  src/api/interfaces/IUser.ts
  src/api/services/User.service.ts
  src/app.ts
  src/config/index.ts
  src/config/storage.config.ts
  src/util/database.connection.ts
  src/util/email.handler.ts
  tsconfig.json
Labels: bug, high-priority, fix

#125 Feature/auth configuration
  src/api/controllers/Event.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IEvent.ts
  src/api/interfaces/index.ts
  src/api/middleware/Auth.middleware.ts
  src/api/models/Event.model.ts
  src/api/models/User.model.ts
  src/api/routes/index.ts
  src/api/services/Event.service.ts
  src/api/services/index.ts
  src/app.ts
Labels: high-priority, fix

#126 Feature/auth configuration
  src/api/controllers/Event.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IEvent.ts
  src/api/routes/index.ts
  src/api/services/Event.service.ts
  src/api/services/index.ts
  src/util/image.handler.ts
Labels: enhancement, high-priority, feature

#128 Fix storage credentials issue
  src/api/interfaces/IConfig.ts
  src/api/middleware/Auth.middleware.ts
  src/api/models/User.model.ts
  src/config/index.ts
  src/config/storage.config.ts
Labels: bug, high-priority, fix

#139 Filter status
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/index.ts
Labels: feature
