Repository ms-club-sliit/msclub-backend, pull requests merged in 2021-11, with the labels that each got.

#2 Create LICENSE
  LICENSE
Labels: documentation, low-priority

#8 Development
  .github/templates/ISSUE_TEMPLATE.md
  .github/templates/PR_TEMPLATE.md
  package-lock.json
  package.json
  src/api/middleware/Auth.middleware.ts
  src/api/middleware/index.ts
  src/api/models/User.model.ts
  src/api/services/User.service.ts
  src/app.ts
  src/config/.env.development
  src/config/Database.connection.ts
  src/util/response.handler.ts
  typings/express/index.d.ts
Labels: high-priority, fix

#11 Add todos for Past and Upcoming Events, Past and Upcoming Webinars , TopSpeakers and their respective models,services,controllers,interfaces and routes
  src/api/controllers/Event.controller.ts
  src/api/controllers/TopSpeaker.controller.ts
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IEvent.ts
  src/api/interfaces/ITopSpeaker.ts
  src/api/interfaces/IWebinar.ts
  src/api/interfaces/index.ts
  src/api/models/Event.model.ts
  src/api/models/TopSpeaker.model.ts
  src/api/models/Webinar.model.ts
  src/api/routes/index.ts
  src/api/services/Event.service.ts
  src/api/services/TopSpeaker.service.ts
  src/api/services/Webinar.service.ts
  src/api/services/index.ts
Labels: good first issue

#16 Implemented the Event Feature
  package-lock.json
  package.json
  src/api/controllers/Event.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IEvent.ts
  src/api/interfaces/index.ts
  src/api/models/Event.model.ts
  src/api/models/User.model.ts
  src/api/routes/index.ts
  src/api/services/Event.service.ts
  src/api/services/index.ts
  src/app.ts
  src/util/database.connection.ts
Labels: feature

#26 Add todo comments for Application Feature
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IApplication.ts
  src/api/interfaces/IEvent.ts
  src/api/interfaces/index.ts
  src/api/models/Application.model.ts
  src/api/models/Event.model.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/index.ts
Labels: documentation

#27 Created Webinar Model
  src/api/interfaces/IWebinar.ts
  src/api/models/Webinar.model.ts
Labels: high-priority, feature

#28 Fixed the bug in Event Feature ( Update and Delete )
  package-lock.json
  package.json
  src/api/controllers/Application.controller.ts
  src/api/controllers/Event.controller.ts
  src/api/controllers/TopSpeaker.controller.ts
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IApplication.ts
  src/api/interfaces/IEvent.ts
  src/api/interfaces/ITopSpeaker.ts
  src/api/interfaces/IWebinar.ts
  src/api/interfaces/index.ts
  src/api/models/Application.model.ts
  src/api/models/Event.model.ts
  src/api/models/TopSpeaker.model.ts
  src/api/models/User.model.ts
  src/api/models/Webinar.model.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/Event.service.ts
  src/api/services/TopSpeaker.service.ts
  src/api/services/Webinar.service.ts
  src/api/services/index.ts
  src/app.ts
  src/util/database.connection.ts
Labels: bug, high-priority

#29 Feature/contact us email sending
  package-lock.json
  package.json
  src/api/controllers/Application.controller.ts
  src/api/controllers/Contact.controller.ts
  src/api/controllers/Event.controller.ts
  src/api/controllers/TopSpeaker.controller.ts
  src/api/controllers/User.controller.ts
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IConfig.ts
  src/api/interfaces/IContact.ts
  src/api/interfaces/IUser.ts
  src/api/interfaces/index.ts
  src/api/models/Contact.model.ts
  src/api/models/User.model.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/Contact.service.ts
  src/api/services/User.service.ts
  src/api/services/Webinar.service.ts
  src/api/services/index.ts
  src/app.ts
  src/config/.env.development
  src/config/.env.production
  src/config/Database.connection.ts
  src/config/index.ts
  src/templates/Contact-Us-Email-Template.html
  src/util/email.handler.ts
Labels: high-priority, feature

#35 webinar services added
  package-lock.json
  src/api/interfaces/index.ts
  src/api/services/Webinar.service.ts
Labels: feature

#33 Feature/todo
  src/api/controllers/ExecutiveBoard.controller.ts
  src/api/interfaces/IBoardMember.ts
  src/api/interfaces/IExecutiveBoard.ts
  src/api/models/BoardMember.model.ts
  src/api/models/ExecutiveBoard.model.ts
  src/api/services/ExecutiveBoard.service.ts
Labels: documentation

#40 webinar controllers added
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/models/Webinar.model.ts
  src/api/routes/index.ts
  src/api/services/index.ts
Labels: feature

#44 Add todos for BoardMember
  src/api/controllers/BoardMember.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/BoardMember.service.ts
Labels: good first issue, high-priority, feature

#49 Created application model and interface Closes #41
  package-lock.json
  src/api/interfaces/IApplication.ts
  src/api/interfaces/index.ts
  src/api/models/Application.model.ts
Labels: feature

#43 Feature/image uploader
  package-lock.json
  package.json
  src/api/controllers/Contact.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IApplication.ts
  src/api/interfaces/IConfig.ts
  src/api/interfaces/IUser.ts
  src/api/models/Application.model.ts
  src/api/routes/index.ts
  src/config/.env.development
  src/config/firebase.config.ts
  src/config/index.ts
  src/config/service-account-file.json
  src/util/image.handler.ts
Labels: low-priority, feature

#45 BoardMember Services added
  src/api/interfaces/IBoardMember.ts
  src/api/interfaces/IExecutiveBoard.ts
  src/api/interfaces/index.ts
  src/api/models/BoardMember.model.ts
  src/api/models/ExecutiveBoard.model.ts
  src/api/services/BoardMember.service.ts
  src/api/services/index.ts
Labels: feature

#52 Implemented top speaker service
  src/api/services/TopSpeaker.service.ts
Labels: feature

#57 Executive and board member controllers , services added
  package-lock.json
  src/api/controllers/BoardMember.controller.ts
  src/api/controllers/ExecutiveBoard.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/routes/topSpeaker.route.ts
  src/api/services/ExecutiveBoard.service.ts
  src/api/services/index.ts
Labels: feature

#53 Feature/top speaker controller
  src/api/controllers/TopSpeaker.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/index.ts
Labels: feature

#61 Fix/event service and controller
  src/api/controllers/Event.controller.ts
  src/api/services/Event.service.ts
Labels: fix

#62 Fix/webinar service and controller
  src/api/controllers/Webinar.controller.ts
  src/api/interfaces/IWebinar.ts
  src/api/models/Webinar.model.ts
  src/api/services/Webinar.service.ts
Labels: fix

#68 Feature/contact us service
  src/api/controllers/Contact.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IContact.ts
  src/api/models/Contact.model.ts
  src/api/routes/index.ts
  src/api/services/Contact.service.ts
  src/api/services/index.ts
  src/templates/Contact-Us-Email-Template.html
  src/util/email.handler.ts
Labels: high-priority, feature

#70 Merge Development into Master branch
  .gitignore
  package-lock.json
  package.json
  src/api/controllers/Application.controller.ts
  src/api/controllers/BoardMember.controller.ts
  src/api/controllers/Contact.controller.ts
  src/api/controllers/Event.controller.ts
  src/api/controllers/ExecutiveBoard.controller.ts
  src/api/controllers/TopSpeaker.controller.ts
  src/api/controllers/User.controller.ts
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/interfaces/IApplication.ts
  src/api/interfaces/IBoardMember.ts
  src/api/interfaces/IConfig.ts
  src/api/interfaces/IContact.ts
  src/api/interfaces/IExecutiveBoard.ts
  src/api/interfaces/ITopSpeaker.ts
  src/api/interfaces/IUser.ts
  src/api/interfaces/IWebinar.ts
  src/api/interfaces/index.ts
  src/api/middleware/index.ts
  src/api/models/Application.model.ts
  src/api/models/BoardMember.model.ts
  src/api/models/Contact.model.ts
  src/api/models/ExecutiveBoard.model.ts
  src/api/models/TopSpeaker.model.ts
  src/api/models/User.model.ts
  src/api/models/Webinar.model.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/BoardMember.service.ts
  src/api/services/Contact.service.ts
  src/api/services/Event.service.ts
  src/api/services/ExecutiveBoard.service.ts
  src/api/services/TopSpeaker.service.ts
  src/api/services/User.service.ts
  src/api/services/Webinar.service.ts
  src/api/services/index.ts
  src/app.ts
  src/config/.env.development
  src/config/.env.production
  src/config/Database.connection.ts
  src/config/firebase.config.ts
  src/config/index.ts
  src/config/service-account-file.json
  src/templates/Contact-Us-Email-Template.html
  src/util/email.handler.ts
  src/util/image.handler.ts
  yarn.lock
Labels: feature

#71 Hotfix/docker build fail
  .gitignore
  package-lock.json
  package.json
  src/util/image.handler.ts
  yarn.lock
Labels: bug, high-priority, fix

#73 Fix the npm start issue
  package.json
  src/config/.env.production
Labels: bug, high-priority, fix

#74 Development
  src/config/.env.development
  src/config/.env.production
  src/config/index.ts
Labels: bug, high-priority, fix

#63 Fixed the bugs in Top Speaker Services
  src/api/services/TopSpeaker.service.ts
Labels: fix

#69 Fix the bugs in Event Services
  src/api/services/Event.service.ts
Labels: fix

#67 Removed todo comments in controllers
  src/api/controllers/BoardMember.controller.ts
  src/api/controllers/ExecutiveBoard.controller.ts
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/BoardMember.service.ts
  src/api/services/Event.service.ts
  src/api/services/ExecutiveBoard.service.ts
  src/api/services/TopSpeaker.service.ts
  src/api/services/index.ts
Labels: low-priority

#75 Fix/board member service
  src/api/services/BoardMember.service.ts
Labels: fix
