Repository ms-club-sliit/msclub-backend, pull requests merged in 2022-02, with the labels that each got.

#180 Admin edit user backend implemented
  src/api/controllers/User.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/User.service.ts
  src/api/services/index.ts
Labels: enhancement, feature

#184 Implement request validation middleware
  package-lock.json
  package.json
  src/api/middleware/Validation.middleware.ts
  src/api/middleware/index.ts
  src/api/routes/index.ts
  src/api/validations/Application.validate.schema.ts
  src/api/validations/index.ts
Labels: enhancement, high-priority, feature

#186 Delete webinar permanantly
  package-lock.json
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Webinar.service.ts
  src/api/services/index.ts
Labels: feature

#192 ACR Deployment
  .github/workflows/acr-development.yaml
  .github/workflows/azure-webapps-node.yml
Labels: enhancement, high-priority

#193 Fix the action failure issue
  .github/workflows/acr-development.yaml
Labels: bug, high-priority, fix

#183 Development
  .github/workflows/development_msdevwebserver.yml
  .github/workflows/master_mswebserver.yml
  Dockerfile
  package-lock.json
  package.json
  src/api/controllers/Contact.controller.ts
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/middleware/Validation.middleware.ts
  src/api/middleware/index.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/Contact.service.ts
  src/api/services/Webinar.service.ts
  src/api/services/index.ts
  src/api/validations/Application.validate.schema.ts
  src/api/validations/index.ts
  src/app.ts
Labels: medium-priority, fix

#190 Delete application from the databse
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/index.ts
Labels: feature

#196 Add storage bucket information
  src/api/controllers/User.controller.ts
Labels: fix

#198 Implemented Remove Inquries permanently from the database
  src/api/controllers/Contact.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Contact.service.ts
  src/api/services/index.ts
Labels: feature

#195 Feature/remove top speaker permenently
  package-lock.json
  src/api/controllers/TopSpeaker.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/TopSpeaker.service.ts
  src/api/services/index.ts
Labels: feature

#199 Feature/setup license
  docs/CODEOWNERS
  src/api/controllers/Application.controller.ts
  src/api/controllers/BoardMember.controller.ts
  src/api/controllers/Contact.controller.ts
  src/api/controllers/Event.controller.ts
  src/api/controllers/ExecutiveBoard.controller.ts
  src/api/controllers/Organization.controller.ts
  src/api/controllers/TopSpeaker.controller.ts
  src/api/controllers/User.controller.ts
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/middleware/Auth.middleware.ts
  src/api/middleware/Validation.middleware.ts
  src/api/middleware/index.ts
  src/api/models/Application.model.ts
  src/api/models/BoardMember.model.ts
  src/api/models/Contact.model.ts
  src/api/models/Event.model.ts
  src/api/models/ExecutiveBoard.model.ts
  src/api/models/Organization.model.ts
  src/api/models/TopSpeaker.model.ts
  src/api/models/User.model.ts
  src/api/models/Webinar.model.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/BoardMember.service.ts
  src/api/services/Contact.service.ts
  src/api/services/Event.service.ts
  src/api/services/ExecutiveBoard.service.ts
  src/api/services/Organization.service.ts
  src/api/services/TopSpeaker.service.ts
  src/api/services/User.service.ts
  src/api/services/Webinar.service.ts
  src/api/services/index.ts
  src/api/validations/Application.validate.schema.ts
  src/api/validations/index.ts
  src/app.ts
  src/config/index.ts
  src/config/storage.config.ts
  src/interfaces/IApplication.ts
  src/interfaces/IBoardMember.ts
  src/interfaces/IConfig.ts
  src/interfaces/IContact.ts
  src/interfaces/IEvent.ts
  src/interfaces/IExecutiveBoard.ts
  src/interfaces/IInterview.ts
  src/interfaces/IOrganization.ts
  src/interfaces/ITopSpeaker.ts
  src/interfaces/IUser.ts
  src/interfaces/IWebinar.ts
  src/interfaces/index.ts
  src/templates/Email-Template.html
  src/util/database.connection.ts
  src/util/email.handler.ts
  src/util/image.handler.ts
  src/util/logger.ts
  src/util/queue.config.ts
  src/util/response.handler.ts
  typings/express/index.d.ts
Labels: enhancement, high-priority
