Repository ms-club-sliit/msclub-backend, pull requests merged in 2022-01, with the labels that each got.

#142 Fixed email goes to spam issue
  package-lock.json
  package.json
  src/api/controllers/Application.controller.ts
  src/api/services/Application.service.ts
  src/app.ts
  src/util/email.handler.ts
Labels: bug

#147 Get deleted applications
  package-lock.json
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/index.ts
Labels: bug, enhancement, feature

#148 Development
  package-lock.json
  src/api/controllers/Application.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/index.ts
Labels: enhancement, high-priority

#149 Fixed Bug in Application Service
  src/api/services/Application.service.ts
Labels: bug

#150 Development
  package-lock.json
  src/api/services/Application.service.ts
Labels: enhancement, high-priority, fix

#153 Add google cloud storage as prod dependency
  package-lock.json
  package.json
Labels: bug, high-priority, fix

#157 Implemented Teams Meeting Schedule Feature
  package.json
  src/api/services/Application.service.ts
  src/interfaces/IInterview.ts
Labels: enhancement, feature

#170 Fixed not updating Webinar Type
  src/api/services/Webinar.service.ts
Labels: fix

#168 Implement server configuration for local environment
  .gitignore
  package-lock.json
  package.json
  src/config/index.ts
Labels: enhancement, high-priority, feature

#163 Implemented recovered deleted webinar
  package-lock.json
  src/api/controllers/Webinar.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Application.service.ts
  src/api/services/Webinar.service.ts
  src/api/services/index.ts
  src/interfaces/IWebinar.ts
Labels: enhancement, feature

#171 Add recover deleted user function
  package.json
  src/api/controllers/TopSpeaker.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/TopSpeaker.service.ts
  src/api/services/index.ts
  tsconfig.json
Labels: enhancement, feature

#174 Fix/Sort List View - Latest to Oldest
  src/api/services/Application.service.ts
  src/api/services/Contact.service.ts
  src/api/services/Event.service.ts
  src/api/services/Webinar.service.ts
Labels: enhancement, fix

#176 Reconfigured routes for get deleted inquiries
  src/api/routes/index.ts
Labels: fix

#177 Corrected routes for deleted inquiries
  src/api/controllers/TopSpeaker.controller.ts
  src/api/routes/index.ts
  src/api/services/TopSpeaker.service.ts
  tsconfig.json
Labels: fix
