Repository ms-club-sliit/msclub-backend, pull requests merged in 2022-03, with the labels that each got.

#210 Reply inquiries feature implemented
  package-lock.json
  src/api/controllers/Contact.controller.ts
  src/api/controllers/index.ts
  src/api/models/Contact.model.ts
  src/api/routes/index.ts
  src/api/services/Contact.service.ts
  src/api/services/index.ts
  src/interfaces/IContact.ts
  src/interfaces/index.ts
Labels: enhancement, high-priority, feature

#216 Face authentication feature
  src/api/controllers/User.controller.ts
  src/api/controllers/index.ts
  src/api/models/User.model.ts
  src/api/routes/index.ts
  src/api/services/User.service.ts
  src/api/services/index.ts
  src/interfaces/IUser.ts
Labels: enhancement, feature

#218 Resolve bugs in face authentication and update user image
  src/api/controllers/User.controller.ts
  src/api/services/User.service.ts
Labels: bug

#221 Delete Meeting (soft delete) controller, service classes created
  src/api/controllers/Meeting.controller.ts
  src/api/controllers/index.ts
  src/api/models/Meeting.model.ts
  src/api/routes/index.ts
  src/api/services/Meeting.service.ts
  src/api/services/index.ts
  src/interfaces/IMeeting.ts
Labels: enhancement, feature
