Repository ms-club-sliit/msclub-backend, pull requests merged in 2022-04, with the labels that each got.

#223 Implement get meeting by id method
  src/api/controllers/Meeting.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Meeting.service.ts
  src/api/services/index.ts
Labels: enhancement, high-priority, feature

#224 Implemented delete meeting permanently function
  src/api/controllers/Meeting.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Meeting.service.ts
  src/api/services/index.ts
Labels: feature

#225 Change request type post -> put
  src/api/routes/index.ts
Labels: fix

#236 Delete internal meetings permanently.
  src/api/services/Meeting.service.ts
Labels: feature

#237 Store interview meeting details
  src/api/controllers/Meeting.controller.ts
  src/api/controllers/index.ts
  src/api/routes/index.ts
  src/api/services/Meeting.service.ts
  src/api/services/index.ts
Labels: enhancement, high-priority, feature
